// Code generated by "stringer -type=QRS"; DO NOT EDIT.

package heartbeat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-0]
	_ = x[V-1]
	_ = x[N-2]
	_ = x[F-3]
	_ = x[P-4]
	_ = x[X-5]
}

const _QRS_name = "AVNFPX"

var _QRS_index = [...]uint8{0, 1, 2, 3, 4, 5, 6}

func (i QRS) String() string {
	if i < 0 || i >= QRS(len(_QRS_index)-1) {
		return "QRS(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QRS_name[_QRS_index[i]:_QRS_index[i+1]]
}
